apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow
data:
  GITSYNC_USERNAME: amF5emVybg==
  GITSYNC_PASSWORD: Z2hwX0NXT1ZBSkVVcUt5VER2cEJZTWtmMUZuSWpzVTVadTBNMFFiVA==
  GIT_SYNC_USERNAME: amF5emVybg==
  GIT_SYNC_PASSWORD: Z2hwX0NXT1ZBSkVVcUt5VER2cEJZTWtmMUZuSWpzVTVadTBNMFFiVA==
