apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow
data:
  GITSYNC_USERNAME: amF5emVybg==
  GITSYNC_PASSWORD: Z2hwX3RoSTNhZVBCYXV5OHN4cmVSODZLVkIxMEdaaVRXcjFPRnRKdA==
  GIT_SYNC_USERNAME: amF5emVybg==
  GIT_SYNC_PASSWORD: Z2hwX3RoSTNhZVBCYXV5OHN4cmVSODZLVkIxMEdaaVRXcjFPRnRKdA==
