name: Push Airflow Image to ECR
on:
  push:
    branches:
      - feature/airflow3.0
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push Docker image
        run: |
          IMAGE_NAME=my-dags
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          echo $IMAGE_NAME:$IMAGE_TAG
